[zabbix-testing]
zabbix-testing-vm ansible_host=192.168.178.100 ansible_user=sre-ubuntu ansible_python_interpreter=/usr/bin/python3

[zabbix-testing:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_become=true
ansible_become_method=sudo
